from optparse import OptionParser

def main():
    parser = OptionParser()
    parser.add_option('-f', '--file', dest='file')
    
    (options, args) = parser.parse_args()
    
    uniq_lines = set()
    freq_dict = {}
    line_count = 0
    
    with open(options.file+".deduped", 'w') as out_f:
        with open(options.file, 'r') as in_f:
            for line in in_f:
                parts = line.split('\t')
                if len(parts) != 2: continue
                line = parts[0].strip()
                line = line[1:-1]   # get rid of quotes around line generated by mrjob
                line = line.replace('\\', '')
                out_f.write('%s\t1\n' %(line))
    

if __name__ == "__main__":
    main()
