application: google-app-engine-django
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
    
- url: /images
  static_dir: public/images    
    
- url: /stylesheets
  static_dir: public/stylesheets

- url: /js
  static_dir: public/javascripts

- url: /media
  static_dir: public/media

- url: /m/.*
  script: ad_server/main.py


- url: /.*
  script: main.py
