COUNTRY_CODE_DICT = {
'AF': r'''Afghanistan''',
'AX': r'''Aland Islands''',
'AL': r'''Albania''',
'DZ': r'''Algeria''',
'AS': r'''American Samoa''',
'AD': r'''andorra''',
'AO': r'''Angola''',
'AI': r'''Anguilla''',
'AQ': r'''Antarctica''',
'AG': r'''Antigua and Barbuda''',
'AR': r'''Argentina''',
'AM': r'''Armenia''',
'AW': r'''Aruba''',
'AU': r'''Australia''',
'AT': r'''Austria''',
'AZ': r'''Azerbaijan''',
'BS': r'''Bahamas''',
'BH': r'''Bahrain''',
'BD': r'''Bangladesh''',
'BB': r'''Barbados''',
'BY': r'''Belarus''',
'BE': r'''Belgium''',
'BZ': r'''Belize''',
'BJ': r'''Benin''',
'BM': r'''Bermuda''',
'BT': r'''Bhutan''',
'BO': r'''Bolivia, Plurinational State of''',
'BQ': r'''Bonaire, Saint Eustatius and Saba''',
'BA': r'''Bosnia and Herzegovina''',
'BW': r'''Botswana''',
'BV': r'''Bouvet Island''',
'BR': r'''Brazil''',
'IO': r'''British Indian Ocean Territory''',
'BN': r'''Brunei darussalam''',
'BG': r'''Bulgaria''',
'BF': r'''Burkina Faso''',
'BI': r'''Burundi''',
'KH': r'''Cambodia''',
'CM': r'''Cameroon''',
'CA': r'''Canada''',
'CV': r'''Cape Verde''',
'KY': r'''Cayman Islands''',
'CF': r'''Central African Republic''',
'TD': r'''Chad''',
'CL': r'''Chile''',
'CN': r'''China''',
'CX': r'''Christmas Island''',
'CC': r'''Cocos (Keeling) Islands''',
'CO': r'''Colombia''',
'KM': r'''Comoros''',
'CG': r'''Congo''',
'CD': r'''Congo, The Democratic Republic of the''',
'CK': r'''Cook Islands''',
'CR': r'''Costa Rica''',
'CI': r'''Cote D'Ivoire''',
'HR': r'''Croatia''',
'CU': r'''Cuba''',
'CW': r'''Curacao''',
'CY': r'''Cyprus''',
'CZ': r'''Czech Republic''',
'DK': r'''Denmark''',
'DJ': r'''Djibouti''',
'DM': r'''Dominica''',
'DO': r'''Dominican Republic''',
'EC': r'''Ecuador''',
'EG': r'''Egypt''',
'SV': r'''El Salvador''',
'GQ': r'''Equatorial Guinea''',
'ER': r'''Eritrea''',
'EE': r'''Estonia''',
'ET': r'''Ethiopia''',
'FK': r'''Falkland Islands (Malvinas)''',
'FO': r'''Faroe Islands''',
'FJ': r'''Fiji''',
'FI': r'''Finland''',
'FR': r'''France''',
'GF': r'''French Guiana''',
'PF': r'''French Polynesia''',
'TF': r'''French Southern Territories''',
'GA': r'''Gabon''',
'GM': r'''Gambia''',
'GE': r'''Georgia''',
'DE': r'''Germany''',
'GH': r'''Ghana''',
'GI': r'''Gibraltar''',
'GR': r'''Greece''',
'GL': r'''Greenland''',
'GD': r'''Grenada''',
'GP': r'''Guadeloupe''',
'GU': r'''Guam''',
'GT': r'''Guatemala''',
'GG': r'''Guernsey''',
'GN': r'''Guinea''',
'GW': r'''Guinea-Bissau''',
'GY': r'''Guyana''',
'HT': r'''Haiti''',
'HM': r'''Heard Island and Mcdonald Islands''',
'VA': r'''Holy See (Vatican City State)''',
'HN': r'''Honduras''',
'HK': r'''Hong Kong''',
'HU': r'''Hungary''',
'IS': r'''Iceland''',
'IN': r'''India''',
'ID': r'''Indonesia''',
'IR': r'''Iran, Islamic Republic of''',
'IQ': r'''Iraq''',
'IE': r'''Ireland''',
'IM': r'''Isle of Man''',
'IL': r'''Israel''',
'IT': r'''Italy''',
'JM': r'''Jamaica''',
'JP': r'''Japan''',
'JE': r'''Jersey''',
'JO': r'''Jordan''',
'KZ': r'''Kazakhstan''',
'KE': r'''Kenya''',
'KI': r'''Kiribati''',
'KP': r'''Korea, Democratic People'S Republic of''',
'KR': r'''Korea, Republic of''',
'KW': r'''Kuwait''',
'KG': r'''Kyrgyzstan''',
'LA': r'''Lao People'S Democratic Republic''',
'LV': r'''Latvia''',
'LB': r'''Lebanon''',
'LS': r'''Lesotho''',
'LR': r'''Liberia''',
'LY': r'''Libyan Arab Jamahiriya''',
'LI': r'''Liechtenstein''',
'LT': r'''Lithuania''',
'LU': r'''Luxembourg''',
'MO': r'''Macao''',
'MK': r'''Macedonia, The Former Yugoslav Republic of''',
'MG': r'''Madagascar''',
'MW': r'''Malawi''',
'MY': r'''Malaysia''',
'MV': r'''Maldives''',
'ML': r'''Mali''',
'MT': r'''Malta''',
'MH': r'''Marshall Islands''',
'MQ': r'''Martinique''',
'MR': r'''Mauritania''',
'MU': r'''Mauritius''',
'YT': r'''Mayotte''',
'MX': r'''Mexico''',
'FM': r'''Micronesia, Federated States of''',
'MD': r'''Moldova, Republic of''',
'MC': r'''Monaco''',
'MN': r'''Mongolia''',
'ME': r'''Montenegro''',
'MS': r'''Montserrat''',
'MA': r'''Morocco''',
'MZ': r'''Mozambique''',
'MM': r'''Myanmar''',
'NA': r'''Namibia''',
'NR': r'''Nauru''',
'NP': r'''Nepal''',
'NL': r'''Netherlands''',
'NC': r'''New Caledonia''',
'NZ': r'''New Zealand''',
'NI': r'''Nicaragua''',
'NE': r'''Niger''',
'NG': r'''Nigeria''',
'NU': r'''Niue''',
'NF': r'''Norfolk Island''',
'MP': r'''Northern Mariana Islands''',
'NO': r'''Norway''',
'OM': r'''Oman''',
'PK': r'''Pakistan''',
'PW': r'''Palau''',
'PS': r'''Palestinian Territory, Occupied''',
'PA': r'''Panama''',
'PG': r'''Papua New Guinea''',
'PY': r'''Paraguay''',
'PE': r'''Peru''',
'PH': r'''Philippines''',
'PN': r'''Pitcairn''',
'PL': r'''Poland''',
'PT': r'''Portugal''',
'PR': r'''Puerto Rico''',
'QA': r'''Qatar''',
'RE': r'''Reunion''',
'RO': r'''Romania''',
'RU': r'''Russian Federation''',
'RW': r'''Rwanda''',
'BL': r'''Saint Barthelemy''',
'SH': r'''Saint Helena, Ascension and Tristan da Cunha''',
'KN': r'''Saint Kitts and Nevis''',
'LC': r'''Saint Lucia''',
'MF': r'''Saint Martin (French Part)''',
'PM': r'''Saint Pierre and Miquelon''',
'VC': r'''Saint Vincent and The Grenadines''',
'WS': r'''Samoa''',
'SM': r'''San Marino''',
'ST': r'''Sao Tome and Principe''',
'SA': r'''Saudi Arabia''',
'SN': r'''Senegal''',
'RS': r'''Serbia''',
'SC': r'''Seychelles''',
'SL': r'''Sierra Leone''',
'SG': r'''Singapore''',
'SX': r'''Sint Maarten (Dutch Part)''',
'SK': r'''Slovakia''',
'SI': r'''Slovenia''',
'SB': r'''Solomon Islands''',
'SO': r'''Somalia''',
'ZA': r'''South Africa''',
'GS': r'''South Georgia and The South Sandwich Islands''',
'ES': r'''Spain''',
'LK': r'''Sri Lanka''',
'SD': r'''Sudan''',
'SR': r'''Suriname''',
'SJ': r'''Svalbard and Jan Mayen''',
'SZ': r'''Swaziland''',
'SE': r'''Sweden''',
'CH': r'''Switzerland''',
'SY': r'''Syrian Arab Republic''',
'TW': r'''Taiwan, Province of China''',
'TJ': r'''Tajikistan''',
'TZ': r'''Tanzania, United Republic of''',
'TH': r'''Thailand''',
'TL': r'''Timor-Leste''',
'TG': r'''Togo''',
'TK': r'''Tokelau''',
'TO': r'''Tonga''',
'TT': r'''Trinidad and Tobago''',
'TN': r'''Tunisia''',
'TR': r'''Turkey''',
'TM': r'''Turkmenistan''',
'TC': r'''Turks and Caicos Islands''',
'TV': r'''Tuvalu''',
'UG': r'''Uganda''',
'UA': r'''Ukraine''',
'AE': r'''United Arab Emirates''',
'GB': r'''United Kingdom''',
'US': r'''United States''',
'UM': r'''United States Minor Outlying Islands''',
'UY': r'''Uruguay''',
'UZ': r'''Uzbekistan''',
'VU': r'''Vanuatu''',
'VE': r'''Venezuela, Bolivarian Republic of''',
'VN': r'''Viet Nam''',
'VG': r'''Virgin Islands, British''',
'VI': r'''Virgin Islands, U.S.''',
'WF': r'''Wallis and Futuna''',
'EH': r'''Western Sahara''',
'YE': r'''Yemen''',
'ZM': r'''Zambia''',
'ZW': r'''Zimbabwe''',
}
