application: mopub-inc
version: 38-admin
runtime: python
api_version: 1
default_expiration: "10d"

builtins:
- datastore_admin: on

handlers:
  
- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt

- url: /images
  static_dir: public/images

- url: /favicon.ico
  static_files: public/images/favicon.ico
  upload: public/images/favicon.ico

- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /placeholders
  static_dir: public/placeholders

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /admin/prep
  script: main.py
  login: admin


- url: /m/clear
  script: ad_server/main.py
  login: admin

- url: /m/.*
  script: ad_server/main.py

- url: /_ah/queue/.*
  script: mopub_logging/views.py
  login: admin  

- url: /.*
  script: main.py
