application: mopub-inc
version: 32-campaigns-django-port
runtime: python
api_version: 1
default_expiration: "10d"

handlers:
- url: /static
  static_dir: static
    
- url: /images
  static_dir: public/images    
    
- url: /stylesheets
  static_dir: public/stylesheets

- url: /js
  static_dir: public/javascripts

- url: /media
  static_dir: public/media

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /stats.*
  script: appstats.py

- url: /m/.*
  script: ad_server/main.py

- url: /.*
  script: main.py
