application: mopub-inc
#application: mopub-experimental
version: 38-risky
runtime: python
api_version: 1
default_expiration: "10d"

builtins:
- datastore_admin: on

# Turn this on to debug
# - appstats: on


handlers:
  
- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt

- url: /images
  static_dir: public/images

- url: /favicon.ico
  static_files: public/images/favicon.ico
  upload: public/images/favicon.ico

# - url: /m/req
#   static_files: public/dummy/req.txt
#   upload: public/dummy/req.txt
  
- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /js/client
  static_dir: public/js/client
  expiration: "30m"

- url: /placeholders
  static_dir: public/placeholders

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /admin/prep
  script: main.py
  login: admin

- url: /reports/gen_report/
  script: main.py
  login: admin
  
- url: /admin/sfdc/
  script: main.py
  login: admin 
  
- url: /m/clear
  script: ad_server/main.py
  login: admin

- url: /files/.*
  script: mopub_logging/views.py
  login: admin

- url: /m/.*
  script: ad_server/main.py

- url: /_ah/queue/.*
  script: mopub_logging/views.py
  login: admin  

- url: /offline/.*
  script: reporting/aws_logging/blob_server.py
    
- url: /.*
  script: main.py
